version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:alpine

    steps:
      - checkout

      - run:
          name: Construir imagen Docker
          command: docker build -t getnasapi .

      - run:
          name: Ejecutar imagen Docker
          command: docker run --name getnasapi getnasapi $apiKey

      - run:
          name: Imprimir resultado en formato JSON
          command: docker cp getnasapi:/app/nasaResults/neowsResponse.json ./output/
          command: cat ./output/neowsResponse.json
