version: 2.1

jobs:
  saluda:
    parameters:
      nombre:
        type: string
        default: elPocho
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo Hola << parameters.nombre >>

workflows:
  workflow1:
    jobs:
      - saluda
  workflow2:
    jobs:
      - saluda:
        nombre: Andy
