version: 2.1

jobs:
  build:
    parameters:
      usuario:
        type: string
        default: '67951926'
    docker:
      image: cimg/base:stable
      auth:
        username: '67951926'
        password: d0ck3RFu_Hub7
    steps:
      - run: echo Hola << parameters.nombre >>

workflows:
  workflow1:
    jobs:
      - saluda
  workflow2:
    jobs:
      - saluda:
          nombre: Andy
