# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    working_directory: .circleci/
    steps:
      - checkout

      - run:
          name: Construir imagen Docker
          command: docker build -t getnasapi .

      - run:
          name: Ejecutar imagen Docker
          command: docker run --name getnasapi getnasapi  $MY_APIKEY_VAR

      - run:
          name: Imprimir resultado en formato JSON
          command: docker cp getnasapi:/app/nasaResults/neowsResponse.json ./output/
            cat ./output/neowsResponse.json
